//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMAClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class PupilAbsence
    {
        public int PupilAbsenceId { get; set; }
        public int AbsenceId { get; set; }
        public int PupilId { get; set; }
    
        public virtual Absence Absence { get; set; }
        public virtual Pupil Pupil { get; set; }
    }
}
