//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMAClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pupil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pupil()
        {
            this.PupilAbsences = new HashSet<PupilAbsence>();
            this.PupilAttendances = new HashSet<PupilAttendance>();
        }
    
        public int PupilId { get; set; }
        public string GivenName { get; set; }
        public string Surname { get; set; }
        public int GuardianId { get; set; }
        public int ClassId { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Guardian Guardian { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PupilAbsence> PupilAbsences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PupilAttendance> PupilAttendances { get; set; }
    }
}
