//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMAClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemEvent
    {
        public int EventId { get; set; }
        public System.DateTime EventDateTime { get; set; }
        public int EventTypeId { get; set; }
        public string EventData { get; set; }
        public int UserId { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual SystemUser SystemUser { get; set; }
    }
}
